version: "3"

services:
  psql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: module12_task05
      POSTGRES_PASSWORD: module12_task05
      POSTGRES_DB: module12_task05