// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewNote struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type NewUser struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type Note struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	User *User  `json:"user"`
}

type Query struct {
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}
